### ISSUE TITLE
why does this put the pubkey in the index name?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-private#1]
what is your reasoning for doing it this way? https://github.com/ssbc/ssb-private/blob/master/index.js#L25

**Comment by mmckegg** [comment]
So that if you use it with a different identity, it will regenerate.

**Comment by dominictarr** [comment]
since the name is part of the flume api, it complicates accessing it as a flumedb. could the name be in the version field instead? normally the version is a number, but a string would still work, changing it would trigger a rebuild.

**Comment by mmckegg** [comment]
Yes, I think that would work!

**Comment by dominictarr** [comment]
oh, also when you say "use a different identity" what are you expecting? are you talking about someone copying their keys across from another computer, or is this part of a UI option?

**Comment by mmckegg** [comment]
> someone copying their keys across from another computer

Yeah, mostly talking about cache invalidation. I think any UI option would be creating a new identity so it wouldn't need to reindex from scratch.

**Comment by dominictarr** [comment]
just to ensure we are on the same page, can you describe how a user changes identity?

**Comment by mmckegg** [comment]
I'm really just talking about when someone manually swaps `secret` files.

I think the best example of when this needs to happen is the "restore key from backup" situation. In this case a user has lost their `~/.ssb` directory but has a backup of their key. To get back on board in patchwork they currently have to start from scratch (with fresh identity) then follow themselves. After this they can swap out their temp secret for the original one.

I think putting the secret id in the version will handle this nicely.

---

The more I think about it though, the less important auto regeneration seems. Looks like the cases where you would want to regenerate are all caused by manually modification anyway. Could just tell people that if they swap secret files, they should also delete the indexes. 

But yeah, good automatic cache invalidation is nice to have!

**Comment by dominictarr** [comment]
got it, perfect. yeah, it doesn't hurt to put the key in the version, lets just do it that way.
