### ISSUE TITLE
Filtering for content fields / what is actually indexed?

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-private#4]
I used this module to make private messages in talenet fast.

To that end it worked but when I tried to filter for `type:post` like [this](https://github.com/talenet/talenet/blob/c9e218cc148f70ce43a12f92f5966989011f00e7/src/renderer/persistence/SSBAdapter.js#L363) it doesn't return anything and I have to add a `pull.filter` to have the wanted effect.

I read [the index.js](https://github.com/ssbc/ssb-private/blob/10150b53b2e595eb7a46578e3baf36c75d6b2a4b/index.js#L29) and I thought this should work since the unboxed value is emitted?

**Comment by mmckegg** [comment]
@cryptix

try `value.content.type` rather than `content.type`.

```js
      query: [{$filter: {
        value: {
          content: { type: 'post' }
        },
        timestamp: {
          // $lte: Number(q.lt) || Date.now(),
          $gte: Number(q.gt) || -Infinity
        }
      }}]
```

However, this won't be much more efficient than just filtering manually because the type field is only queryable if you also specify an author (`ATY` index). This will just use [map-filter-reduce](https://github.com/dominictarr/map-filter-reduce) to filter the results of the timestamp index (`TSP`). 

https://github.com/ssbc/ssb-private/blob/10150b53b2e595eb7a46578e3baf36c75d6b2a4b/index.js#L8-L11
